# Redis Cache and Session Store Services

version: '3.8'

services:
  redis-master:
    image: redis:7-alpine
    container_name: lms-redis-master
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
      - ./databases/redis/redis.conf:/etc/redis/redis.conf:ro
    networks:
      - lms-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ["redis-server", "/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD}"]
    labels:
      - "lms.service.type=cache"
      - "lms.service.name=redis-master"
      - "lms.service.description=Redis master instance"

  redis-replica-1:
    image: redis:7-alpine
    container_name: lms-redis-replica-1
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_replica_1_data:/data
      - ./databases/redis/redis-replica.conf:/etc/redis/redis.conf:ro
    depends_on:
      - redis-master
    networks:
      - lms-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ["redis-server", "/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD}", "--replicaof", "redis-master", "6379"]
    labels:
      - "lms.service.type=cache"
      - "lms.service.name=redis-replica-1"
      - "lms.service.description=Redis replica instance 1"

  redis-replica-2:
    image: redis:7-alpine
    container_name: lms-redis-replica-2
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_replica_2_data:/data
      - ./databases/redis/redis-replica.conf:/etc/redis/redis.conf:ro
    depends_on:
      - redis-master
    networks:
      - lms-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ["redis-server", "/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD}", "--replicaof", "redis-master", "6379"]
    labels:
      - "lms.service.type=cache"
      - "lms.service.name=redis-replica-2"
      - "lms.service.description=Redis replica instance 2"
