# MinIO Object Storage Service

version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: lms-minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
    volumes:
      - minio_data:/data
      - ./storage/minio/config:/root/.minio:ro
    networks:
      - lms-internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: server /data --console-address ":9001"
    labels:
      - "lms.service.type=storage"
      - "lms.service.name=minio"
      - "lms.service.description=Object storage for files and media"
